services:
  ros2:
    container_name: ros2-jazzy-dev
    init: true
    stdin_open: true
    tty: true
    build:
      context: .
      args:
        WORKSPACE: ${WORKSPACE:-dev_ws}
    image: ${IMAGE_NAME:-ros2-jazzy-dev}:${IMAGE_TAG:-latest}

    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu, graphics, compute, utility, display]

    network_mode: host
    ipc: host
    privileged: true

    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
      - TERM=xterm-256color
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility,graphics,display
      - ROS_DISTRO=jazzy
      - RMW_IMPLEMENTATION=${RMW_IMPLEMENTATION:-rmw_cyclonedds_cpp}
      - ROS_DOMAIN_ID=${ROS_DOMAIN_ID:-0}
      - CYCLONEDDS_URI=file:///root/cyclonedds.xml
      - WGPU_BACKEND=gl
      - LD_PRELOAD=/usr/lib/x86_64-linux-gnu/libssl.so.3

    volumes:
      - ${HOME}/${WORKSPACE:-dev_ws}:/root/${WORKSPACE:-dev_ws}:rw
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ${HOME}/.Xauthority:/root/.Xauthority:ro
      - ./utilities:/utilities:rw

    devices:
      - /dev/bus/usb:/dev/bus/usb
      - /dev/input/js1:/dev/input/js1

    command: >
      bash -lc "
        source /opt/ros/jazzy/setup.bash &&
        if [ -f /root/${WORKSPACE:-dev_ws}/install/setup.bash ]; then
          source /root/${WORKSPACE:-dev_ws}/install/setup.bash;
        fi &&
        tail -f /dev/null"